app/urls.py
from django.contrib import admin
from django.urls import path
from app import views


urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
]

main_app/urls.py
from django.urls import path
from . import views

app_name = 'main_app'

"""
path(route, view, kwargs, name)
第一引数(URL)にアクセスがあった時、第二引数の関数を呼び出し、第三引数にnameを設定する。
この name 属性は、テンプレート内でURLを参照するために使用されます。
"""
urlpatterns = [
    path('', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('user_home/', views.user_home, name='user_home'),
    path('user_home/auth_info/', views.auth_info, name='auth_info'),
    path('user_home/auth_info_saved/', views.update_auth_info, name='update_auth_info'),
    path('user_home/matching_profile/', views.matching_profile, name='matching_profile'),
    path('user_home/matching_profile_saved/', views.update_matching_profile, name='update_matching_profile'),
]

matching/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('matching_app/', include('matching_app.urls')), 
    path('messages/', include('messages_app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

matching_app/urls.py
from django.urls import path
from . import views

app_name = 'matching_app'

urlpatterns = [
    path('roommate_preference/', views.roommate_preference, name='roommate_preference'),
    path('update_roommate_preference/', views.update_roommate_preference, name='update_roommate_preference'),
    path('matching/new_users/', views.match_new_users, name='match_new_users'),
    path('matching/recommend_users/', views.match_recommend_users, name='match_recommend_users'),
    path('matching/search_users/', views.match_search_users, name='match_search_users'),
    path('matching/user_detail/<int:user_id>/', views.user_detail, name='user_detail'),
]

messages_app/urls.py
from django.urls import path
from . import views

app_name = 'messages_app'

urlpatterns = [
    path('list/', views.message_list, name='message_list'),
    path('view_chat/<str:receiver_id>/', views.view_chat, name='view_chat'),
    path('send_message/<int:receiver_id>/<uuid:chat_id>/', views.send_message_view, name='send_message_view'),
]

main_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from .models import UserProfile, UserPurpose, UserDesiredCohabitee, UserRoomLayout, UserRent
from matching.constants.choices import (
    PURPOSE_CHOICES, DESIRED_COHABITEE_CHOICES, LAYOUT_CHOICES, RENT_CHOICES,
    GENDER_CHOICES, OCCUPATION_CHOICES, PREFECTURE_CHOICES, SMOKING_CHOICES,
    PET_CHOICES, PARKING_CHOICES, COMMUTE_TIME_CHOICES, PERIOD_CHOICES
)


class UserUpdateForm(UserChangeForm):
    password = None  # パスワード変更を無効化
    new_password = forms.CharField(
        required=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        label="新しいパスワード"
    )
    password_confirm = forms.CharField(
        required=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        label="新しいパスワードの確認"
    )

    class Meta:
        model = User
        fields = ['username', 'email', 'new_password', 'password_confirm']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
        }

    def clean(self):
        cleaned_data = super().clean()
        new_password = cleaned_data.get("new_password")
        password_confirm = cleaned_data.get("password_confirm")

        if new_password != password_confirm:
            self.add_error("password_confirm", "パスワードが一致しません")




class UserProfileForm(forms.ModelForm):
    
    class Meta:
        model = UserProfile
        fields = [
            'user_name', 
            'profile_image', 
            'sex', 
            'day_of_birth', 
            'profession', 
            'prefecture', 
            'period', 
            'is_smoker', 
            'has_pets', 
            'parking', 
            'self_introduction',
        ]
        labels = {
            'user_name': 'あなたの使用するネームを記入してください',
            'profile_image': 'プロフィール画像を選択してください',
            'sex': '性別を選択してください',
            'day_of_birth': '生年月日を入力してください',
            'profession': '職業を入力してください',
            'prefecture': 'お住まいの都道府県を選択してください',
            'period': '希望する入居期間を選択してください',
            'is_smoker': '喫煙者ですか？',
            'has_pets': 'ペットを飼っていますか？',
            'parking': '駐車場は必要ですか？',
            'self_introduction': '自己紹介を記入してください',
        }
        widgets = {
            'user_name': forms.TextInput(attrs={'class': 'form-control'}), 
            'profile_image': forms.FileInput(attrs={'class': 'form-control'}), 
            'sex': forms.Select(choices=GENDER_CHOICES, attrs={'class': 'form-control'}), 
            'day_of_birth': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'profession': forms.TextInput(attrs={'class': 'form-control'}), 
            'prefecture': forms.Select(choices=PREFECTURE_CHOICES, attrs={'class': 'form-control'}), 
            'period': forms.Select(choices=PERIOD_CHOICES, attrs={'class': 'form-control'}), 
            'is_smoker': forms.Select(choices=SMOKING_CHOICES, attrs={'class': 'form-control'}), 
            'has_pets': forms.Select(choices=PET_CHOICES, attrs={'class': 'form-control'}), 
            'parking': forms.Select(choices=PARKING_CHOICES, attrs={'class': 'form-control'}), 
            'self_introduction': forms.Textarea(attrs={'class': 'form-control'}),
        }


class UserPurposeForm(forms.ModelForm):
    purpose_name = forms.MultipleChoiceField(
        choices=PURPOSE_CHOICES, 
        label='あなたのルームシェアの目的は何ですか？', 
        widget=forms.CheckboxSelectMultiple(),
    )
    class Meta:
        model = UserPurpose
        fields = ['purpose_name']
        widgets = {
            'user': forms.HiddenInput(),
        }

class UserDesiredCohabiteeForm(forms.ModelForm):
    cohabitation_number = forms.MultipleChoiceField(
        choices=DESIRED_COHABITEE_CHOICES, 
        label='希望する同居人数は何人ですか？', 
        widget=forms.CheckboxSelectMultiple(),
    )
    class Meta:
        model = UserDesiredCohabitee
        fields = ['cohabitation_number']
        widgets = {
            'user': forms.HiddenInput(),
        }

class UserRoomLayoutForm(forms.ModelForm):
    layout = forms.MultipleChoiceField(
        choices=LAYOUT_CHOICES, 
        label='希望する部屋の間取りは何ですか？', 
        widget=forms.CheckboxSelectMultiple()
    )
    class Meta:
        model = UserRoomLayout
        fields = ['layout']
        widgets = {
            'user': forms.HiddenInput(),
        }

class UserRentForm(forms.ModelForm):
    rent = forms.MultipleChoiceField(
        choices=RENT_CHOICES, 
        label='希望する家賃はいくらですか？', 
        widget=forms.CheckboxSelectMultiple(),
    )
    class Meta:
        model = UserRent
        fields = ['rent']
        widgets = {
            'user': forms.HiddenInput(),
        }


from .models import Profile, Prefecture

class ProfileForm(forms.ModelForm):
    current_prefecture = forms.ModelChoiceField(queryset=Prefecture.objects.all())
    favorite_prefectures = forms.ModelMultipleChoiceField(queryset=Prefecture.objects.all(), required=False)
    
    class Meta:
        model = Profile
        fields = ['current_prefecture', 'favorite_prefectures']

main_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.exceptions import ValidationError
from matching.constants.instructions_data  import instructions
from django.db import IntegrityError, DatabaseError
from .forms import (
    UserUpdateForm, UserProfileForm, UserPurposeForm,
    UserDesiredCohabiteeForm, UserRoomLayoutForm, UserRentForm
)
from .models import (
    UserProfile, UserPurpose, UserDesiredCohabitee,
    UserRoomLayout, UserRent, Prefecture
)
from matching_app.models import RoommatePreference
from django.contrib import messages


def get_initial_model_form(request, model_class, form_class, field_name):
    """
    ユーザーに関連するデータを取得し、指定されたフォームクラスの初期化を行います。
    データは、指定されたモデルクラスとフィールド名に基づいてフィルタリングされます。
    (この処理はユーザー1対N個のデータ関係を持つmodelに対して繰り返し処理を行う際を想定して作成。)
    引数:
    request (HttpRequest): ユーザーからのリクエスト情報を含む HttpRequest オブジェクト。
    model_class (Model): データを取得するために使用されるモデルクラス。
    form_class (Form): データを初期化するために使用されるフォームクラス。
    field_name (str): モデルインスタンスから取得するフィールド名。
    
    戻り値:
    form (form_class): 初期化されたフォームクラスのインスタンス。
    
    例:
    user_data_form = get_initial_model_form(request, UserProfile, UserProfileForm, 'hobby')
    """
    objects = model_class.objects.filter(user=request.user)
    initial_model_form = form_class(initial={field_name: [getattr(object, field_name) for object in objects]})
    return initial_model_form


def get_matching_profile_context(request):
    # リクエストユーザーに関連するデータを取得し、初期化したフォームクラスを返す。
    purpose_form = get_initial_model_form(request, UserPurpose, UserPurposeForm, 'purpose_name')
    cohabitation_form = get_initial_model_form(request, UserDesiredCohabitee, UserDesiredCohabiteeForm, 'cohabitation_number')
    layout_form = get_initial_model_form(request, UserRoomLayout, UserRoomLayoutForm, 'layout')
    rent_form = get_initial_model_form(request, UserRent, UserRentForm, 'rent')
    user_profile_form = UserProfileForm(instance=UserProfile.objects.get(user=request.user))
    profile_form = Prefecture.objects.all()
    
    context = {
        'purpose_form': purpose_form,
        'cohabitation_form': cohabitation_form,
        'layout_form': layout_form,
        'rent_form': rent_form,
        'roommate_preference_form': user_profile_form,
        'profile_form': profile_form,
    }
    return context


def update_user_data(request, model_class, model_form, field_name):
    # 既存のデータを削除してから新しいデータを保存
    try:
        model_class.objects.filter(user=request.user).delete()        
        dates = model_form.cleaned_data[field_name]
        for date in dates:
            instance = model_class(user=request.user, **{field_name: date})
            instance.save()
    except ValidationError as ve:
        raise ValueError(f"Validation error updating {model_class.__name__}: {str(ve)}")
    except Exception as e:
        raise ValueError(f"Error updating {model_class.__name__}: {str(e)}")


def signup(request):
    # POST時にバリテーションがTureであればユーザー登録を行い、ログイン状態でユーザーホーム画面を返す。
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('main_app:user_home')
        else:
            return render(request, 'main_app/signup.html', {'form': form})
    return render(request, 'main_app/signup.html')


def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('main_app:user_home')
        else:
            messages.error(request, 'ログインに失敗しました。ユーザー名とパスワードを確認してください。')
            return render(request, 'main_app/login.html', {'form': form})
    else:
        form = AuthenticationForm()
        return render(request, 'main_app/login.html', {'form': form})


def logout(request):
    # ログアウト後、TOP画面を返す
    auth_logout(request)
    return redirect('main_app:signup')


@login_required
def user_home(request):
    # ユーザープロフィール、アプリの使用方法を表示
    user_profile = UserProfile.objects.get(user=request.user)
    context = {
        'user_profile': user_profile,
        'instructions': instructions
    }
    return render(request, 'main_app/user_home.html',context)


@login_required
def auth_info(request):
    # 認証情報の表示
    if request.method == 'GET':
        form = UserUpdateForm(instance=request.user)
        return render(request, 'main_app/auth_info.html', {'form': form})


@login_required
def update_auth_info(request):
    # 認証情報の更新
    if request.method == 'POST':
        form = UserUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            try:
                user = form.save(commit=False)
                new_password = form.cleaned_data.get("new_password")
                if new_password:
                    user.set_password(new_password)
                user.save()
                
                if new_password:
                    messages.success(request, 'プロフィールが更新されました！再度ログインしてください。')
                    logout(request)
                    return redirect('main_app:login')
                else:
                    messages.success(request, 'プロフィールが更新されました！')
                    return redirect('main_app:auth_info')
                
            except IntegrityError as e:
                messages.error(request, f"データベースの整合性エラーが発生しました: {e}")
            except DatabaseError as e:
                messages.error(request, f"データベースエラーが発生しました: {e}")
            except Exception as e:
                messages.error(request, f"予期しないエラーが発生しました: {e}")
            return render(request, 'main_app/auth_info.html', {'form': form})
        else:
            for field, errors in form.errors.items():
                for error in errors:
                    messages.error(request, f"{field}: {error}")
            return render(request, 'main_app/auth_info.html', {'form': form})
    return redirect('main_app:auth_info')



@login_required
def matching_profile(request):
    # リクエストユーザーに関連するデータを取得し、初期化したフォームクラスを返す。
    if request.method == 'GET':
        context = get_matching_profile_context(request)
        return render(request, 'main_app/matching_profile.html', context)


@login_required
def update_matching_profile(request):
    if request.method == 'POST':
        try:
            # PSOTされたデータのフォーム作成
            purpose_form = UserPurposeForm(request.POST)
            cohabitation_form = UserDesiredCohabiteeForm(request.POST)
            layout_form = UserRoomLayoutForm(request.POST)
            rent_form = UserRentForm(request.POST)
            user_profile = UserProfile.objects.get(user=request.user)
            user_profile_form = UserProfileForm(request.POST, request.FILES, instance=user_profile)
            
            # バリデーション
            if (purpose_form.is_valid() and 
                cohabitation_form.is_valid() and
                layout_form.is_valid() and 
                rent_form.is_valid() and 
                user_profile_form.is_valid()):
                
                # 1対Nのモデルのデータを更新
                update_user_data(request, UserPurpose, purpose_form, 'purpose_name')
                update_user_data(request, UserDesiredCohabitee, cohabitation_form, 'cohabitation_number')
                update_user_data(request, UserRoomLayout, layout_form, 'layout')
                update_user_data(request, UserRent, rent_form, 'rent')
                
                # 1対1のモデルのデータを更新
                user_profile_form.save()
                
                messages.success(request, 'プロフィールが更新されました！')
        except ValueError as ve:
            messages.error(request, f"プロフィールの更新に失敗しました： {str(ve)}")
        
        # リクエストユーザーに関連するデータを取得し、初期化したフォームクラスを返す。
        context = get_matching_profile_context(request)
        return render(request, 'main_app/matching_profile.html', context)

main_app/templates/main_app/auth_info.html
{% extends 'main_app/base.html' %}

{% block content %}
{% include 'main_app/menu_buttons.html' %}

<style>
    .account-settings-card {
        max-width: 600px;
        margin: auto;
        padding: 30px;
        background-color: #f5f5f5;
        border-radius: 5px;
        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);
    }
    .account-settings-icon {
        font-size: 48px;
        margin-bottom: 20px;
        color: #007bff;
    }
</style>

<div class="account-settings-card">
    <div class="text-center">
        <i class="bi bi-pencil-square account-settings-icon"></i>
        <h2 class="mb-4">アカウント設定</h2>
    </div>
    <!-- message -->
    {% if messages %}
      <ul class="messages">
        {% for message in messages %}
          {% if message.tags == 'success' %}
            <li class="alert alert-success" role="alert">{{ message }}</li>
          {% elif message.tags == 'error' %}
            <li class="alert alert-danger" role="alert">{{ message }}</li>
          {% else %}
            <li class="alert alert-info" role="alert">{{ message }}</li>
          {% endif %}
        {% endfor %}
      </ul>
    {% endif %}
    <!-- account settings -->
    <form method="post" action="{% url 'main_app:update_auth_info' %}" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">更新</button>
    </form>
</div>

{% endblock content %}

main_app/templates/main_app/base.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>RoomShareMatch</title>
    <!-- Bootstrap CSS -->
    <link 
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" 
        rel="stylesheet" 
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" 
        crossorigin="anonymous"
    >
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.0/css/all.min.css">

    <style>
       .navbar {
           background-color: #1F2E35 !important;
       }
       .nav-item {
           margin-left: 10px;
       }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark">
    <div class="container">
        <img src="{% static 'images/logo.jpg' %}" alt="ロゴ" style="height: 40px; margin-right: 10px;">
        {% if user.is_authenticated %}
        <a class="navbar-brand" href="{% url 'main_app:user_home' %}">RoomShareMatch</a>
        {% else %}
        <a class="navbar-brand" href="{% url 'main_app:signup' %}">RoomShareMatch</a>
        {% endif %}
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav">
            {% if user.is_authenticated %}
            <li class="nav-item"><a class="nav-link" href="{% url 'main_app:auth_info' %}"><i class="bi bi-gear"></i> アカウント設定</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'main_app:logout' %}"><i class="bi bi-box-arrow-right"></i> {% trans "ログアウト" %}</a></li>
            {% else %}
            <li class="nav-item"><a class="nav-link" href="{% url 'main_app:login' %}"><i class="bi bi-box-arrow-in-right"></i> {% trans "ログイン" %}</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'main_app:signup' %}"><i class="bi bi-person-plus"></i> {% trans "登録" %}</a></li>
            {% endif %}
            </ul>
        </div>
    </div>
    </nav>
    <main class="container my-4">
        {% block content %}
        {% endblock content %}
    </main>
    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"></script>
</body>
</html>

main_app/templates/main_app/login.html
{% extends 'main_app/base.html' %}
{% block content %}
<style>
    .login-card {
        max-width: 400px;
        margin: auto;
        padding: 30px;
        background-color: #f5f5f5;
        border-radius: 5px;
        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);
    }
    .login-icon {
        font-size: 48px;
        margin-bottom: 20px;
        color: #007bff;
    }
</style>

<div class="login-card">
    <div class="text-center">
        <i class="bi bi-box-arrow-in-right login-icon"></i>
        <h2 class="mb-4">ログイン</h2>
    </div>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
            {% if message.tags == 'success' %}
                <li class="alert alert-success" role="alert">{{ message }}</li>
            {% elif message.tags == 'error' %}
                <li class="alert alert-danger" role="alert">{{ message }}</li>
            {% else %}
                <li class="alert alert-info" role="alert">{{ message }}</li>
            {% endif %}
        {% endfor %}
    </ul>
    {% endif %}
    {% if form.non_field_errors %}
    <div class="alert alert-danger">
        {{ form.non_field_errors }}
    </div>
    {% endif %}
    <form method="POST">
        {% csrf_token %}
        <div class="mb-3">
            <label for="username" class="form-label">ユーザー名</label>
            <input type="text" class="form-control" id="username" name="username" value="{{ form.username.value|default:'' }}" required>
            {% if form.username.errors %}
            <div class="alert alert-danger mt-2">
                {{ form.username.errors }}
            </div>
            {% endif %}
        </div>
        <div class="mb-3">
            <label for="password" class="form-label">パスワード</label>
            <input type="password" class="form-control" id="password" name="password" required>
            {% if form.password.errors %}
            <div class="alert alert-danger mt-2">
                {{ form.password.errors }}
            </div>
            {% endif %}
        </div>
        <button type="submit" class="btn btn-primary">ログイン</button>
    </form>
</div>
{% endblock content %}

main_app/templates/main_app/matching_profile.html
{% extends 'main_app/base.html' %}

{% block content %}
{% include 'main_app/menu_buttons.html' %}

<h2><i class="bi bi-pencil-square"></i> プロフィール編集</h2>
<!-- message -->
{% if messages %}
  <ul class="messages">
    {% for message in messages %}
      {% if message.tags == 'success' %}
        <li class="alert alert-success" role="alert">{{ message }}</li>
      {% elif message.tags == 'error' %}
        <li class="alert alert-danger" role="alert">{{ message }}</li>
      {% else %}
        <li class="alert alert-info" role="alert">{{ message }}</li>
      {% endif %}
    {% endfor %}
  </ul>
{% endif %}
<!-- profile -->
<div class="card mt-4">
  <div class="card-body" style="background-color: #f8f9fa;">
    <h5 class="card-title">プロフィール情報</h5>
    <p class="card-text"></p>
      <form method="post" action="{% url 'main_app:update_matching_profile' %}" enctype="multipart/form-data">
        {% csrf_token %}
        {{ purpose_form.as_p }}
        {{ cohabitation_form.as_p }}
        {{ layout_form.as_p }}
        {{ rent_form.as_p }}
        {{ roommate_preference_form.as_p }}
        {{ profile_form.as_p }}
        
        <button type="submit" class="btn btn-primary">保存</button>
      </form>
  </div>
</div>
{% endblock content %}

main_app/templates/main_app/menu_buttons.html
<div class="card">
    <div class="card-body" style="background-color: #f8f9fa;">
        <a href="{% url 'main_app:user_home' %}" class="btn btn-outline-primary"><i class="bi bi-house"></i> ホーム</a>
        <a href="{% url 'main_app:matching_profile' %}" class="btn btn-outline-primary"><i class="bi bi-pencil-square"></i> プロフィール設定</a>
        <a href="{% url 'matching_app:roommate_preference' %}" class="btn btn-outline-primary"><i class="bi bi-sliders"></i> ルームシェア希望設定</a>
        <a href="{% url 'matching_app:match_new_users' %}" class="btn btn-outline-primary"><i class="bi bi-shuffle"></i> マッチング</a>
        <a href="{% url 'messages_app:message_list' %}" class="btn btn-outline-primary"><i class="bi bi-chat-dots"></i> ダイレクトメッセージ一覧</a>
    </div>
</div>
<hr class="my-4">

main_app/templates/main_app/signup.html
{% extends 'main_app/base.html' %}
{% block content %}
<style>
    .signup-card {
        max-width: 400px;
        margin: auto;
        padding: 30px;
        background-color: #f5f5f5;
        border-radius: 5px;
        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);
    }
    .signup-icon {
        font-size: 48px;
        margin-bottom: 20px;
        color: #007bff;
    }
</style>

<div class="signup-card">
    <div class="text-center">
        <i class="bi bi-person-plus signup-icon"></i>
        <h2 class="mb-4">アカウント作成</h2>
    </div>
    <form method="post" action="{% url 'main_app:signup' %}">
        {% csrf_token %}
        <div class="mb-3">
            <label for="username" class="form-label">ユーザー名:</label>
            <input type="text" class="form-control" name="username" required>
            {% if form.username.errors %}
                {% for error in form.username.errors %}
                <div class="alert alert-danger mt-2">{{ error }}</div>
                {% endfor %}
            {% endif %}
        </div>
        <div class="mb-3">
            <label for="password1" class="form-label">パスワード:</label>
            <input type="password" class="form-control" name="password1" required>
            {% if form.password1.errors %}
                {% for error in form.password1.errors %}
                <div class="alert alert-danger mt-2">{{ error }}</div>
                {% endfor %}
            {% endif %}
        </div>
        <div class="mb-3">
            <label for="password2" class="form-label">パスワード再入力:</label>
            <input type="password" class="form-control" name="password2" required>
            {% if form.password2.errors %}
                {% for error in form.password2.errors %}
                <div class="alert alert-danger mt-2">{{ error }}</div>
                {% endfor %}
            {% endif %}
        </div>
        <button type="submit" class="btn btn-primary">登録</button>
    </form>
    <div class="mt-3 text-center">
        <p>既にアカウントをお持ちの方は<a href="{% url 'main_app:login' %}">こちらからログイン</a></p>
    </div>
</div>
{% endblock content %}

main_app/templates/main_app/user_home.html
{% extends 'main_app/base.html' %}
{% block content %}
{% include 'main_app/menu_buttons.html' %}
<h2><i class="bi bi-house"></i>ホーム</h2>
<div class="card">
    <div class="card-body" style="background-color: #f8f9fa;">
        <h5 class="card-title">こんにちは、{{ user.username }} さん！</h5>
        <div class="row">
            <div class="col-md-4">
                <img src="{{ user_profile.profile_image.url }}" alt="プロフィール画像" class="img-thumbnail" style="width: 150px; height: 150px;">
            </div>
            <div class="col-md-8">
                <p>名前: {{ user_profile.user_name|default:"未登録" }} <i class="bi bi-person"></i></p>
                <p>性別: {{ user_profile.sex|default:"未登録" }} 
                    {% if user_profile.sex == "男性" %}<i class="bi bi-gender-male"></i>
                    {% elif user_profile.sex == "女性" %}<i class="bi bi-gender-female"></i>
                    {% else %}<i class="bi bi-gender-trans"></i>
                    {% endif %}
                </p>
                <p>誕生日: {{ user_profile.day_of_birth|default:"未登録" }} <i class="bi bi-calendar"></i></p>
                <p>自己紹介: {{ user_profile.self_introduction|default:"未登録" }} </p>
            </div>
        </div>
    </div>
</div>
<div class="mt-3">
    <h3>アプリの使い方</h3>
    <ol>
        {% for title, content in instructions.items %}
        <li>
            <h4>{{ title }}</h4>
            <p>{{ content }}</p>
        </li>
        {% endfor %}
    </ol>
</div>
{% endblock content %}