app/urls.py
from django.contrib import admin
from django.urls import path
from app import views


urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
]

matching/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('matching_app/', include('matching_app.urls')), 
    path('messages/', include('messages_app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

matching_app/urls.py
from django.urls import path
from . import views

app_name = 'matching_app'

urlpatterns = [
    path('roommate_preference/', views.roommate_preference, name='roommate_preference'),
    path('update_roommate_preference/', views.update_roommate_preference, name='update_roommate_preference'),
    path('matching/new_users/', views.match_new_users, name='match_new_users'),
    path('matching/recommend_users/', views.match_recommend_users, name='match_recommend_users'),
    path('matching/search_users/', views.match_search_users, name='match_search_users'),
    path('matching/user_detail/<int:user_id>/', views.user_detail, name='user_detail'),
]

messages_app/urls.py
from django.urls import path
from . import views

app_name = 'messages_app'

urlpatterns = [
    path('list/', views.message_list, name='message_list'),
    path('view_chat/<str:receiver_id>/', views.view_chat, name='view_chat'),
    path('send_message/<int:receiver_id>/<uuid:chat_id>/', views.send_message_view, name='send_message_view'),
]

messages_app/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid
import os

def unique_file_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = f'{uuid.uuid4()}.{ext}'
    return os.path.join('message_images', filename)


class Chat(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    participants = models.ManyToManyField(User, related_name='chats')


class Message(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sent_messages')
    chat = models.ForeignKey(Chat, on_delete=models.CASCADE, related_name='messages')
    content = models.TextField()
    image = models.ImageField(upload_to=unique_file_path, null=True, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    def __str__(self):
        return f"Message(id={self.id}, chat={self.chat}, sender={self.sender}, content={self.content}, timestamp={self.timestamp})"

messages_app/forms.py
# messages_app/forms.py

from django import forms
from .models import Message

class SendMessageForm(forms.ModelForm):
    content = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    image = forms.ImageField(required=False)

    class Meta:
        model = Message
        fields = ['content', 'image']

messages_app/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .models import Chat, Message
from main_app.models import UserProfile
from django.views.decorators.http import require_POST
from django.urls import reverse
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse


def create_or_get_chat(user1, user2):
    """
    ユーザー1とユーザー2のチャットオブジェクトを作成または取得します。
    
    :param user1: Userオブジェクト
    :param user2: Userオブジェクト
    :return: Chatオブジェクト
    """
    is_chat = Chat.objects.filter(participants=user1).filter(participants=user2).exists()
    if is_chat:
        chat = Chat.objects.filter(participants=user1).filter(participants=user2).first()
    else:
        chat = Chat.objects.create()
        chat.participants.set([user1, user2])
        chat.save()
    return chat


@login_required
def view_chat(request, receiver_id):
    """
    ユーザーが指定したチャット相手とのチャット画面を表示します。
    
    :param request: HttpRequestオブジェクト
    :param receiver_id: 整数（受信者のユーザーID）
    :return: HttpResponseオブジェクト
    """
    receiver = get_object_or_404(User, pk=receiver_id)
    if receiver:
        # chat,messages取得
        chat = create_or_get_chat(request.user, receiver)
        messages = Message.objects.filter(chat=chat).order_by('timestamp')
        
        # 相手のメッセージを既読にする
        Message.objects.filter(chat=chat, sender=receiver).update(is_read=True)
        
        receiver_profile_image = UserProfile.objects.get(user=receiver).profile_image.url
        
        content = {
            'chat_id': chat.id,
            'messages': messages,
            'receiver': receiver,
            'receiver_profile_image': receiver_profile_image
        }
        return render(request, 'messages_app/chat_view.html', content)



def send_message(sender, chat, content, image=None):
    """
    送信者からチャットにメッセージを送信します。
    
    :param sender: Userオブジェクト（メッセージの送信者）
    :param chat: Chatオブジェクト
    :param content: 文字列（メッセージの内容）
    :param image: Fileオブジェクト（アップロードされた画像ファイル、任意）
    :return: Messageオブジェクト
    """
    message = Message(sender=sender, chat=chat, content=content, image=image)
    message.save()
    return message


@login_required
@require_POST
def send_message_view(request, receiver_id, chat_id):
    """
    ユーザーが指定したチャット相手にメッセージを送信します。
    
    :param request: HttpRequestオブジェクト
    :param receiver_id: 整数（受信者のユーザーID）
    :return: HttpResponseRedirectオブジェクト
    """
    receiver = get_object_or_404(User, pk=receiver_id)
    chat = get_object_or_404(Chat, pk=chat_id)
    if receiver and chat:
        content = request.POST['content']
        image = request.FILES.get('image', None)
        send_message(request.user, chat, content, image)
        # Message.objects.create(sender=request.user, chat=chat, content=content)
        messages = Message.objects.filter(chat=chat).order_by('timestamp')
        content = {
            'chat_id': chat.id,
            'receiver': receiver,
            'messages': messages,            
        }
        return HttpResponseRedirect(reverse('messages_app:view_chat', args=[receiver_id]))  



@login_required
def message_list(request):
    user = request.user
    chats = Chat.objects.filter(participants=user)
    
    chat_data = []
    for chat in chats:
        last_message = Message.objects.filter(chat=chat).order_by('-timestamp').first()
        chat_partner = next(participant for participant in chat.participants.all() if participant != user)
        chat_partner_user_name = UserProfile.objects.get(user=chat_partner).user_name
        print(chat_partner_user_name)
        chat_partner_profile_image = UserProfile.objects.get(user=chat_partner).profile_image.url
        chat_data.append({
            'id': chat.id,
            'partner': chat_partner,
            'partner_user_name': chat_partner_user_name,
            'last_message': last_message,
            'timestamp': last_message.timestamp if last_message else None,
            'partner_profile_image': chat_partner_profile_image
        })
    
    context = {'chats': chat_data}
    return render(request, 'messages_app/message_list.html', context)

messages_app/templates/messages_app/chat_view.html
{% extends 'main_app/base.html' %}
{% load static %}
{% block content %}
{% include 'main_app/menu_buttons.html' %}
<h2 class="mb-4"><i class="bi bi-chat-dots"></i>ダイレクトメッセージ</h2>
<div class="container mt-4">
  <div class="d-flex w-100 justify-content-between">
    <div>
      <img src="{{ receiver_profile_image }}" alt="プロフィール画像" style="width: 75px; height: 75px;">
      <a href="{% url 'matching_app:user_detail' receiver.id %}" class="mb-1 d-inline">{{ receiver.username }}</a>
    </div>
</div>
  <div class="row">
    <div class="col-md-8">
      <div class="card">
        <div class="card-body" style="height: 70vh; overflow-y: auto;">
          {% for message in messages %}
            <div class="d-flex mb-3 {% if message.sender == request.user %}justify-content-end{% else %}justify-content-start{% endif %}">
              <div>
                {% if message.sender != request.user %}
                  <!-- <div class="mb-1"><strong>{{ message.sender.username }}</strong></div> -->
                {% endif %}
                <div class="card {% if message.sender == request.user %}bg-info{% else %}bg-light{% endif %} py-2 px-3 rounded">
                  <p class="card-text mb-0  {% if message.sender != request.user %}text-dark{% endif %}">{{ message.content }}</p>
                  {% if message.image %}
                    <img src="{{ message.image.url }}" class="img-thumbnail mt-2" alt="Image">
                  {% endif %}
                </div>
                <div class="mt-1">
                  <small>{{ message.timestamp|date:"Y-m-d H:i" }}</small>
                  {% if message.sender == request.user and not message.is_read %}
                    <small>未読</small>
                  {% elif message.sender == request.user and  message.is_read %}
                    <small>既読</small>
                  {% endif %}
                </div>
              </div>
            </div>
          {% empty %}
            <div class="card bg-light py-2 px-3 rounded mb-3">
              <p class="card-text mb-0">まだメッセージがありません。</p>
            </div>
          {% endfor %}
        </div>
        <div class="card-footer">
          <form method="post" action="{% url 'messages_app:send_message_view' receiver.id chat_id %}" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="input-group">
              <input type="text" name="content" class="form-control" placeholder="Send a message...">
              <input type="file" name="image" class="form-control" accept="image/*">  <!-- 画像アップロード用のフィールドを追加 -->
              <button type="submit" class="btn btn-primary">Send</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

messages_app/templates/messages_app/message_list.html
{% extends 'main_app/base.html' %}
{% block content %}
{% include 'main_app/menu_buttons.html' %}
<h2 class="mb-4"><i class="bi bi-chat-dots"></i>ダイレクトメッセージ</h2>
<div class="list-group">
    {% for chat in chats %}
        <a href="{% url 'messages_app:view_chat' chat.partner.id %}" class="list-group-item list-group-item-action" >
            <div class="d-flex w-100 justify-content-between">
                <div>
                    <img src="{{ chat.partner_profile_image }}" alt="プロフィール画像" style="width: 50px; height: 50px;">
                    <h5 class="mb-1 d-inline">{{ chat.partner_user_name }}</h5>
                </div>
                <small>{{ chat.timestamp|date:"Y-m-d H:i" }}</small>
            </div>
            <p class="mb-1">{{ chat.last_message.content|truncatechars:50 }}</p>
        </a>
    {% empty %}
        <div class="list-group-item">
            まだチャットはありません。
        </div>
    {% endfor %}
</div>
{% endblock %}