app/urls.py
from django.contrib import admin
from django.urls import path
from app import views


urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
]

matching/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('matching_app/', include('matching_app.urls')), 
    path('messages/', include('messages_app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

matching_app/urls.py
from django.urls import path
from . import views

app_name = 'matching_app'

urlpatterns = [
    path('roommate_preference/', views.roommate_preference, name='roommate_preference'),
    path('update_roommate_preference/', views.update_roommate_preference, name='update_roommate_preference'),
    path('matching/new_users/', views.match_new_users, name='match_new_users'),
    path('matching/recommend_users/', views.match_recommend_users, name='match_recommend_users'),
    path('matching/search_users/', views.match_search_users, name='match_search_users'),
    path('matching/user_detail/<int:user_id>/', views.user_detail, name='user_detail'),
]

messages_app/urls.py
from django.urls import path
from . import views

app_name = 'messages_app'

urlpatterns = [
    path('list/', views.message_list, name='message_list'),
    path('view_chat/<str:receiver_id>/', views.view_chat, name='view_chat'),
    path('send_message/<int:receiver_id>/<uuid:chat_id>/', views.send_message_view, name='send_message_view'),
]

matching_app/models.py
'''
前章のMTVフレームワークで触れたM（モデル）の部分であり、DBに登録するテーブルを記述していきます。
基本的にはClassベースで記述していき、最終的にmigrateというアクションでデータ構造をデータベースに登録します。
'''

from django.db import models
from django.contrib.auth.models import User


# ルームシェア希望条件を表すモデルクラス(単一な回答の場合フィールドのみまとめたモデル)
class RoommatePreference(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='roommate_preference')
    gender = models.CharField(max_length=6, verbose_name='性別')
    age_min = models.IntegerField(blank=True, null=True, verbose_name='最小年齢')
    age_max = models.IntegerField(blank=True, null=True, verbose_name='最大年齢')
    occupation = models.CharField(max_length=10, verbose_name='職業')
    period = models.CharField(max_length=10, verbose_name='期間')
    smoking = models.CharField(max_length=10, verbose_name='喫煙')
    pet = models.CharField(max_length=10, verbose_name='ペット')
    prefecture = models.CharField(max_length=10, verbose_name='都道府県')
    commute_time = models.CharField(max_length=10, verbose_name='通勤時間')
    parking = models.CharField(max_length=10, verbose_name='駐車場')

# 目的
class Purpose(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='purposes')
    purpose_name = models.CharField(max_length=200, verbose_name='目的名')
    

# 同居人数
class DesiredCohabitee(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='desired_cohabitees')
    cohabitation_number = models.CharField(max_length=30, verbose_name='同居人数')
    

# 部屋の間取り
class RoomLayout(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='room_layout')
    layout = models.CharField(max_length=50, verbose_name='間取り')
    

# 家賃
class Rent(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='rent')
    rent = models.CharField(max_length=100, verbose_name='家賃')
    
    
    def show_gender(self):
        return self.gender
    
    def get_age_range(self):
        return f"{self.age_min}歳〜{self.age_max}歳"

matching_app/forms.py
from django import forms
from .models import Purpose, DesiredCohabitee, RoomLayout, Rent, RoommatePreference
from .choices import (
    PURPOSE_CHOICES, DESIRED_COHABITEE_CHOICES, LAYOUT_CHOICES, 
    RENT_CHOICES, GENDER_CHOICES, OCCUPATION_CHOICES, 
    PREFECTURE_CHOICES, SMOKING_CHOICES, PET_CHOICES, 
    PARKING_CHOICES, COMMUTE_TIME_CHOICES, PERIOD_CHOICES,AGE_CHOICES
)


class PurposeForm(forms.ModelForm):
    purpose_name = forms.MultipleChoiceField(
        choices=PURPOSE_CHOICES, 
        widget=forms.CheckboxSelectMultiple, 
        label='あなたが望むルームシェアの相手の目的は何ですか？'
    )
    
    class Meta:
        model = Purpose
        fields = ['purpose_name']

class DesiredCohabiteeForm(forms.ModelForm):
    cohabitation_number = forms.MultipleChoiceField(
        choices=DESIRED_COHABITEE_CHOICES, 
        widget=forms.CheckboxSelectMultiple, 
        label='あなたが望むルームシェアの相手の同居人数はどのくらいですか？'
    )
    
    class Meta:
        model = DesiredCohabitee
        fields = ['cohabitation_number']

class RoomLayoutForm(forms.ModelForm):
    layout = forms.MultipleChoiceField(
        choices=LAYOUT_CHOICES, 
        widget=forms.CheckboxSelectMultiple, 
        label='あなたが望むルームシェアの相手の希望間取りはどのようなものですか？'
    )
    
    class Meta:
        model = RoomLayout
        fields = ['layout']

class RentForm(forms.ModelForm):
    rent = forms.MultipleChoiceField(
        choices=RENT_CHOICES, 
        widget=forms.CheckboxSelectMultiple, 
        label='あなたが望むルームシェアの相手の家賃希望範囲はどのくらいですか？'
    )
    
    class Meta:
        model = Rent
        fields = ['rent']




class RoommatePreferenceForm(forms.ModelForm):
    class Meta:
        model = RoommatePreference
        fields = [
            'gender', 
            'age_min', 
            'age_max', 
            'occupation', 
            'period', 
            'prefecture', 
            'smoking', 
            'pet', 
            'commute_time',
            'parking', 
        ]
        labels = {
            'gender': 'どの性別のルームメイトを希望しますか？',
            'age_min': '希望するルームメイトの最小年齢は？',
            'age_max': '希望するルームメイトの最大年齢は？',
            'occupation': '希望するルームメイトの職業は？',
            'period': '希望するルームメイトの入居期間は？',
            'prefecture': '希望するルームメイトの都道府県は？',
            'smoking': '喫煙するルームメイトを希望しますか？',
            'pet': 'ペットを飼っているルームメイトを希望しますか？',
            'commute_time': '希望するルームメイトの最寄駅からの距離は？',
            'parking': '駐車場を利用するルームメイトを希望しますか？',
        }
        widgets = {
            'gender': forms.RadioSelect(choices=GENDER_CHOICES),
            'age_min': forms.Select(choices=AGE_CHOICES),
            'age_max': forms.Select(choices=AGE_CHOICES),
            'occupation': forms.RadioSelect(choices=OCCUPATION_CHOICES),
            'period': forms.RadioSelect(choices=PERIOD_CHOICES),
            'prefecture': forms.Select(choices=PREFECTURE_CHOICES),
            'smoking': forms.RadioSelect(choices=SMOKING_CHOICES),
            'pet': forms.RadioSelect(choices=PET_CHOICES),
            'commute_time': forms.RadioSelect(choices=COMMUTE_TIME_CHOICES),
            'parking': forms.RadioSelect(choices=PARKING_CHOICES),
        }

matching_app/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.db import transaction
from .forms import PurposeForm, DesiredCohabiteeForm, RoomLayoutForm, RentForm, RoommatePreferenceForm
from .models import Purpose, DesiredCohabitee, RoomLayout, Rent, RoommatePreference
from main_app.models import UserProfile
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from django.db.models import Q
from datetime import date
from datetime import timedelta
from django.core.exceptions import ValidationError
from django.contrib import messages
from main_app.views import get_initial_model_form, update_user_data
from sklearn.metrics.pairwise import cosine_similarity
from dateutil.relativedelta import relativedelta
import pandas as pd
from matching.constants.choices import (
    PURPOSE_CHOICES, DESIRED_COHABITEE_CHOICES, LAYOUT_CHOICES, RENT_CHOICES,
    GENDER_CHOICES, OCCUPATION_CHOICES, PREFECTURE_CHOICES, SMOKING_CHOICES,
    PET_CHOICES, PARKING_CHOICES, COMMUTE_TIME_CHOICES, PERIOD_CHOICES
)


def get_roommate_preference_context(request):
    # リクエストユーザーに関連するデータを取得し、初期化したフォームクラスを返す。
    purpose_form = get_initial_model_form(request, Purpose, PurposeForm, 'purpose_name')
    cohabitation_form = get_initial_model_form(request, DesiredCohabitee, DesiredCohabiteeForm, 'cohabitation_number')
    layout_form = get_initial_model_form(request, RoomLayout, RoomLayoutForm, 'layout')
    rent_form = get_initial_model_form(request, Rent, RentForm, 'rent')
    roommate_preference_form = RoommatePreferenceForm(instance=RoommatePreference.objects.get(user=request.user))
    
    context = {
        'purpose_form': purpose_form,
        'cohabitation_form': cohabitation_form,
        'layout_form': layout_form,
        'rent_form': rent_form,
        'roommate_preference_form': roommate_preference_form,
    }
    return context


@login_required
def roommate_preference(request):
    # リクエストユーザーに関連するデータを取得し、初期化したフォームクラスを返す。
    if request.method == 'GET':
        context = get_roommate_preference_context(request)
        return render(request, 'matching_app/roommate_preference.html', context)


@login_required
@transaction.atomic
def update_roommate_preference(request):
    if request.method == 'POST':
        try:
            # PSOTされたデータのフォーム作成
            purpose_form = PurposeForm(request.POST)
            cohabitation_form = DesiredCohabiteeForm(request.POST)
            layout_form = RoomLayoutForm(request.POST)
            rent_form = RentForm(request.POST)        
            roommate_preference_form = RoommatePreferenceForm(request.POST)
            roommate_preference_form = RoommatePreferenceForm(request.POST, instance=RoommatePreference.objects.get_or_create(user=request.user)[0])
            
            # バリデーション
            if (purpose_form.is_valid() and 
                cohabitation_form.is_valid() and 
                layout_form.is_valid() and 
                rent_form.is_valid() and 
                roommate_preference_form.is_valid()):
                
                # 1対Nのモデルのデータを更新
                update_user_data(request, Purpose, purpose_form, 'purpose_name')
                update_user_data(request, DesiredCohabitee, cohabitation_form, 'cohabitation_number')
                update_user_data(request, RoomLayout, layout_form, 'layout')
                update_user_data(request, Rent, rent_form, 'rent')
                
                # 1対1のモデルのデータを更新
                roommate_preference_form.save()
                
                messages.success(request, 'プロフィールが更新されました！')
        except ValueError as ve:
            messages.error(request, f"プロフィールの更新に失敗しました： {str(ve)}")
        
        context = get_roommate_preference_context(request)
        return render(request, 'matching_app/roommate_preference.html', context)


@login_required
def user_detail(request, user_id):
    target_user = get_object_or_404(User, pk=user_id)
    user_profile = get_object_or_404(UserProfile, user=target_user)
    
    # Additional models
    roommate_preference = get_object_or_404(RoommatePreference, user=target_user)
    purposes = Purpose.objects.filter(user=target_user)
    desired_cohabitees = DesiredCohabitee.objects.filter(user=target_user)
    room_layouts = RoomLayout.objects.filter(user=target_user)
    rents = Rent.objects.filter(user=target_user)
    context = {
        'user': target_user,
        'profile': user_profile,
        'roommate_preference': roommate_preference,
        'purposes': purposes,
        'desired_cohabitees': desired_cohabitees,
        'room_layouts': room_layouts,
        'rents': rents,
    }
    return render(request, 'matching_app/user_detail.html', context)


@login_required
def match_new_users(request):
    """
    # Get the current page number from the query parameters, default is 1
    # DBからユーザーの登録日時が最新のユーザーを取得 (リクエストユーザーを除く)
    # Create a Paginator object with the users and the number of users per page
    # Get the users for the current page
    # ユーザーオブジェクトのユーザ名, 年齢のオブジェクトを作成
    """
    current_page = int(request.GET.get('page', 1))
    all_users = User.objects.exclude(pk=request.user.pk).order_by('-date_joined')
    paginator = Paginator(all_users, 5)
    latest_users = paginator.get_page(current_page)
    users = []
    for user in latest_users:
        try:
            user_profile = UserProfile.objects.get(user=user)
            users.append({
                'id': user.id,
                'user_name': user_profile.user_name,
                'profile_image': user_profile.profile_image,
                'age': user_profile.age,
                'sex': user_profile.sex,
            })
        except UserProfile.DoesNotExist:
            continue
    # Render the match_new.html template with the users and pagination information
    return render(request, 'matching_app/match_new.html', {
        'users': users,
        'current_page': current_page,
        'has_next': latest_users.has_next(),
        'has_previous': current_page > 1,  # 追加
    })


@login_required
def match_search_users(request):
    queryset = UserProfile.objects.exclude(user=request.user)
    search_params = {
        'keyword': request.GET.get('keyword', ''),
        'sex': request.GET.get('sex', ''),
        'min_age': request.GET.get('min_age', ''),
        'max_age': request.GET.get('max_age', ''),
        'prefecture': request.GET.get('prefecture', ''),
    }
    
    # Check if any search parameter is present
    if any(search_params.values()):
        if search_params['keyword']:
            queryset = queryset.filter(self_introduction__icontains=search_params['keyword'])
        if search_params['sex']:
            queryset = queryset.filter(sex=search_params['sex'])
        if search_params['min_age']:
            min_birthdate = date.today() - relativedelta(years=int(search_params['min_age']))
            queryset = queryset.filter(day_of_birth__lte=min_birthdate)
        if search_params['max_age']:
            max_birthdate = date.today() - relativedelta(years=int(search_params['max_age']) + 1) + timedelta(days=1)
            queryset = queryset.filter(day_of_birth__gt=max_birthdate)
        if search_params['prefecture']:
            queryset = queryset.filter(prefecture=search_params['prefecture'])

        users = [
            {
                'id': user.user.id,
                'username': user.user.username,
                'user_name': user.user_name,
                'profile_image': user.profile_image,
                'age': user.age,
                'sex': user.sex,
                'prefecture': user.prefecture,
                'self_introduction': user.self_introduction,
            }
            for user in queryset
        ]
    else:
        users = []

    context = {
        'users': users, 
        'search_params': search_params, 
        'prefecture_choices': PREFECTURE_CHOICES
    }
    return render(request, 'matching_app/match_search.html', context)








def get_filtered_users(request, queryset=None):
    if queryset is None:
        queryset = UserProfile.objects.exclude(user=request.user)
    search_params = request.GET
    if 'keyword' in search_params and search_params['keyword']:
        queryset = queryset.filter(Q(user_name__icontains=search_params['keyword']) | Q(self_introduction__icontains=search_params['keyword']))
    if 'sex' in search_params and search_params['sex']:
        queryset = queryset.filter(sex=search_params['sex'])
    if 'min_age' in search_params and search_params['min_age']:
        min_birthdate = date.today() - relativedelta(years=int(search_params['min_age']) + 1) + timedelta(days=1)
        queryset = queryset.filter(day_of_birth__gt=min_birthdate)
    if 'max_age' in search_params and search_params['max_age']:
        max_birthdate = date.today() - relativedelta(years=int(search_params['max_age']))
        queryset = queryset.filter(day_of_birth__lte=max_birthdate)
    users = []
    for user_profile in queryset:
        users.append({
            'id': user_profile.user.id,
            'username': user_profile.user.username,
            'profile_image': user_profile.profile_image,
            'age': user_profile.age,
            'sex': user_profile.sex,
        })
    return users



def calculate_cosine_similarity(a, b):
    return cosine_similarity([a], [b])[0][0]

from django.core.files import File
def match_recommend_users(request):
    # 前処理
    analyze_fields = {
        "sex": GENDER_CHOICES, 
        "prefecture": PREFECTURE_CHOICES, 
        "period": PERIOD_CHOICES,  
        "is_smoker": SMOKING_CHOICES, 
        "has_pets": PET_CHOICES, 
        "parking": PARKING_CHOICES,
    }

    field_dicts = {}
    for field, choices in analyze_fields.items():
        field_dict = {}
        for index, (value, _) in enumerate(choices):

matching_app/templates/matching_app/match_new.html
{% extends 'main_app/base.html' %}
{% load static %}
{% block content %}
{% include 'main_app/menu_buttons.html' %}
{% include 'matching_app/match_type_menu_buttons.html' %}

<h2 class="mb-4"><i class="bi bi-clock"></i> 新着マッチング</h2>
<!-- 新着マッチングの表示部分 -->
{% for user in users %}
<div class="card mb-1" style="background-color: #f8f9fa;">
    <div class="row g-0">
        <div class="col-md-4">
            {% if user.profile_image %}
            <img src="{{ user.profile_image.url }}" class="img-fluid rounded-start" alt="プロフィール画像" style="width: 180px; height: 180px;">
            {% else %}
            <img src="{% static 'media/profile_images/default.jpg' %}" class="img-fluid rounded-start" alt="プロフィール画像" style="width: 180px; height: 180px;">
            {% endif %}
        </div>
        <div class="col-md-8">
            <div class="card-body" >
                <p class="card-text">ユーザー名: {{ user.user_name|default:"未登録" }}</p>
                <p class="card-text">年齢: {{ user.age|default:"未登録" }}</p>
                <p class="card-text">性別: {{ user.sex|default:"未登録" }}</p>
                <a href="{% url 'matching_app:user_detail' user.id %}" class="btn btn-primary">詳細を見る</a>
            </div>
        </div>
    </div>
</div>
{% endfor %}
<!-- Back and Next buttons -->
<div class="d-flex justify-content-between">
    {% if current_page|add:"-1" >= 1 %}
    <a href="{% url 'matching_app:match_new_users' %}?page={{ current_page|add:'-1' }}" class="btn btn-primary">戻る</a>
    {% else %}
    <a class="btn btn-primary disabled">戻る</a>
    {% endif %}
    {% if has_next %}
    <a href="{% url 'matching_app:match_new_users' %}?page={{ current_page|add:'1' }}" class="btn btn-primary">次へ</a>
    {% endif %}
</div>
{% endblock content %}

matching_app/templates/matching_app/match_recomend.html
{% extends 'main_app/base.html' %}
{% load static %}
{% block content %}
{% include 'main_app/menu_buttons.html' %}
{% include 'matching_app/match_type_menu_buttons.html' %}

<h2 class="mb-4"><i class="bi bi-people-fill"></i> おすすめマッチング</h2>
<!-- おすすめマッチングの表示部分 -->
{% for user in recommended_users %}
<div class="card mb-1" style="background-color: #f8f9fa;">
    <div class="row g-0">

        
        <div class="col-md-4">
            {% if user.profile_image %}
            <img src="{{ user.profile_image }}" class="img-fluid rounded-start" alt="プロフィール画像" style="width: 180px; height: 180px;">
            {% else %}
            <img src="{% static 'media/profile_images/default.jpg' %}" class="img-fluid rounded-start" alt="プロフィール画像" style="width: 180px; height: 180px;">
            {% endif %}
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <p class="card-text">ユーザー名: {{ user.user_name|default:"未登録" }}</p>
                <p class="card-text">年齢: {{ user.age|default:"未登録" }}</p>
                <p class="card-text">性別: {{ user.sex|default:"未登録" }}</p>
                <p class="card-text">相性: {{ user.similarity }}%</p>
                <a href="{% url 'matching_app:user_detail' user.id %}" class="btn btn-primary">詳細を見る</a>
            </div>
        </div>
    </div>
</div>
{% empty %}
<div class="alert alert-info" role="alert">
    おすすめのユーザーが見つかりませんでした。
</div>
{% endfor %}
{% endblock content %}

matching_app/templates/matching_app/match_search.html
{% extends 'main_app/base.html' %}
{% load static %}
{% block content %}
{% include 'main_app/menu_buttons.html' %}
{% include 'matching_app/match_type_menu_buttons.html' %}

<h2 class="mb-4"><i class="bi bi-search"></i> 検索マッチング</h2>
<!-- 検索フォーム -->
<form class="mb-4" method="get" action="{% url 'matching_app:match_search_users' %}">
    <div class="input-group">
        <input type="text" class="form-control" name="keyword" placeholder="キーワード" value="{{ search_params.keyword }}">
        <select class="form-select" name="sex" value="{{ search_params.sex }}">
          <option value="">性別を選択</option>
          <option value="男性" {% if search_params.sex == "男性" %}selected{% endif %}>男性</option>
          <option value="女性" {% if search_params.sex == "女性" %}selected{% endif %}>女性</option>
      </select>
        <input type="number" class="form-control" name="min_age" placeholder="最小年齢" value="{{ search_params.min_age }}">
        <input type="number" class="form-control" name="max_age" placeholder="最大年齢" value="{{ search_params.max_age }}">
        <select class="form-select" name="prefecture" value="{{ search_params.prefecture }}">
          <option value="">都道府県を選択</option>
          <!-- 都道府県のリストを追加 -->
          {% for code, name in prefecture_choices %}
          <option value="{{ code }}" {% if search_params.prefecture == code %}selected{% endif %}>{{ name }}</option>
          {% endfor %}
        </select>
        <button type="submit" class="btn btn-primary"><i class="bi bi-search"></i>検索</button>
    </div>
</form>

<!-- 検索結果の表示部分 -->
{% for user in users %}
<div class="card mb-1" style="background-color: #f8f9fa;">
    <div class="row g-0">
        <div class="col-md-4">
            {% if user.profile_image %}
            <img src="{{ user.profile_image.url }}" class="img-fluid rounded-start" alt="プロフィール画像" style="width: 180px; height: 180px;">
            {% else %}
            <img src="{% static 'media/profile_images/default.jpg' %}" class="img-fluid rounded-start" alt="プロフィール画像" style="width: 180px; height: 180px;">
            {% endif %}
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <p class="card-text">ユーザー名: {{ user.user_name|default:"未登録" }}</p>
                <p class="card-text">年齢: {{ user.age|default:"未登録" }}</p>
                <p class="card-text">性別: {{ user.sex|default:"未登録" }}</p>
                <p class="card-text">都道府県: {{ user.prefecture|default:"未登録" }}</p>
                <p class="card-text">自己紹介: {{ user.self_introduction|default:"未登録" }}</p>
                <a href="{% url 'matching_app:user_detail' user.id %}" class="btn btn-primary">詳細を見る</a>
            </div>
        </div>
    </div>
</div>
{% empty %}
<div class="alert alert-info" role="alert">

    検索条件に一致するユーザーが見つかりませんでした。
</div>
{% endfor %}
{% endblock content %}

matching_app/templates/matching_app/match_type_menu_buttons.html
<div class="card">
  <div class="card-body" style="background-color: #f8f9fa;">
    <a href="{% url 'matching_app:match_new_users' %}" class="btn btn-outline-primary me-2"><i class="bi bi-clock"></i> 新着マッチング</a>
    <a href="{% url 'matching_app:match_recommend_users' %}" class="btn btn-outline-primary me-2"><i class="bi bi-star"></i> リコメンドマッチング</a>
    <a href="{% url 'matching_app:match_search_users' %}" class="btn btn-outline-primary"><i class="bi bi-search"></i> 検索マッチング</a>
  </div>
</div>
<hr class="my-4">

matching_app/templates/matching_app/roommate_preference.html
{% extends 'main_app/base.html' %}

{% block content %}
{% include 'main_app/menu_buttons.html' %}
<h2><i class="bi bi-sliders"></i> ルームシェア希望条件設定</h2>
<!-- message -->
{% if messages %}
  <ul class="messages">
    {% for message in messages %}
      {% if message.tags == 'success' %}
        <li class="alert alert-success" role="alert">{{ message }}</li>
      {% elif message.tags == 'error' %}
        <li class="alert alert-danger" role="alert">{{ message }}</li>
      {% else %}
        <li class="alert alert-info" role="alert">{{ message }}</li>
      {% endif %}
    {% endfor %}
  </ul>
{% endif %}
<div class="card mt-4">
  <div class="card-body" style="background-color: #f8f9fa;">
    <form method="POST" action="{% url 'matching_app:update_roommate_preference' %}">
      {% csrf_token %}
      {{ purpose_form.as_p }}
      {{ cohabitation_form.as_p }}
      {{ layout_form.as_p }}
      {{ rent_form.as_p }}
      {{ roommate_preference_form.as_p }}
      <div class="form-group row mt-4">
        <div class="col-sm-10">
          <button type="submit" class="btn btn-primary">保存</button>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock content %}

matching_app/templates/matching_app/user_detail.html
{% extends 'main_app/base.html' %}

{% block content %}
{% include 'main_app/menu_buttons.html' %}
<h2 class="mb-4">ユーザー詳細</h2>
<div class="row">
    <div class="col-md-4">
        {% load static %}
        <div class="card mb-3">
            <div class="card-body text-center">
                {% if profile.profile_image %}
                    <img src="{{ profile.profile_image.url }}" alt="プロフィール画像" class="img-thumbnail">
                {% else %}
                    <img src="{% static 'media/profile_images/default.jpg' %}" alt="プロフィール画像" class="img-thumbnail">
                {% endif %}
            </div>
        </div>
        <a href="{% url 'messages_app:view_chat' user.id %}" class="btn btn-primary"><i class="bi bi-chat-dots"></i> ダイレクトメッセージ</a>
    </div>
    
    <div class="col-md-8">
        <div class="card mb-3">
            <div class="card-header bg-primary text-white">プロフィール情報</div>
            <div class="card-body">
                <p>ユーザー名: {{ profile.user_name|default:"未登録" }}</p>
                <p>性別: {{ profile.sex|default:"未登録" }}</p>
                <p>生年月日: {{ profile.day_of_birth|default:"未登録" }}</p>
                <p>年齢: {{ profile.age|default:"未登録" }}</p>
                <p>職業: {{ profile.profession|default:"未登録" }}</p>
                <p>都道府県: {{ profile.prefecture|default:"未登録" }}</p>
                <p>期間: {{ profile.period|default:"未登録" }}</p>
                <p>喫煙: {{ profile.is_smoker|default:"未登録" }}</p>
                <p>ペット: {{ profile.has_pets|default:"未登録" }}</p>
                <p>駐車場: {{ profile.parking|default:"未登録" }}</p>
                <p>自己紹介: {{ profile.self_introduction|default:"未登録" }}</p>
            </div>
        </div>
        <div class="card mb-3">
            <div class="card-header bg-primary text-white">マッチング希望条件</div>
            <div class="card-body">
                <div class="col-md-6">
                    <p>性別: {{ roommate_preference.gender|default:"未登録" }}</p>
                    <p>年齢: {{ roommate_preference.age_min|default:"未登録" }}歳〜 {{ roommate_preference.age_max|default:"未登録" }}歳</p>
                    <p>職業: {{ roommate_preference.occupation|default:"未登録" }}</p>
                    <p>期間: {{ roommate_preference.period|default:"未登録" }}</p>
                    <p>喫煙: {{ roommate_preference.smoking|default:"未登録" }}</p>
                    <p>ペット: {{ roommate_preference.pet|default:"未登録" }}</p>
                    <p>都道府県: {{ roommate_preference.prefecture|default:"未登録" }}</p>
                    <p>通勤時間: {{ roommate_preference.commute_time|default:"未登録" }}</p>
                    <p>駐車場: {{ roommate_preference.parking|default:"未登録" }}</p>
                </div>
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock content %}
    